version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: hcsp-{{ checksum "pom.xml" }}
      - run:
          name: Run Maven verify
          command: mvn clean verify -PmavenCentral
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: hcsp-{{ checksum "pom.xml" }}
workflows:
  version: 2
  default:
    jobs:
      - test